### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [mrdunk/wafer#4]
Hello, under what license is this project released under ? I would like to study it to learn more about SketchUp scripting. Thank-you.

**Comment by mrdunk** [comment]
Thanks for the reminder.
MIT licence added.

I would not recommend this as a starting place to learn about Sketchup scripting; i first wrote it back in 2010 when i had very little programming experience.
To date it is still the only Sketchup plugin or Ruby code i have ever written so it is unlikely to conform to best practices.
